- go.mod
- go.sum
- nexus/resource_repository.go
- Update go-nexus-client to v0.8.2
- Implement repository update
> Implement repository update

- nexus/resource_blobstore.go
- nexus/resource_blobstore_file_test.go
- nexus/resource_blobstore_s3_test.go
> Make blobstore type S3 attribute bucket_security optional

- .github/workflows/release.yml
- .goreleaser.yml
set env so build are also statically linked
> fix(goreleaser): set static linked builds

- nexus/resource_privilege.go
> added pattern parameter to nexus_privilege resource

- go.mod
- nexus/resource_repository.go
I know, @Nosmoht already started to work on this fix, but I did it on my fork, and ready to share.
> Support password field for proxy client

- .github/workflows/release.yml
- .goreleaser.yml
> fix(signing): enable signing

- nexus/resource_privilege.go
- nexus/resource_privilege_test.go
This PR requires: https://github.com/datadrivers/go-nexus-client/pull/42 to be merged.
> Script privilege

- docs/resources/blobstore.md
- nexus/resource_blobstore.go
- nexus/resource_blobstore_file_test.go
> Change documentation of soft limit at resource `nexus_blobstore` and add validation function for the minimum value

- docs/resources/blobstore.md
- docs/resources/security_ldap_order.md
- nexus/resource_blobstore.go
- nexus/resource_security_ldap_order.go
> Fix documentation of blobstore

- docs/data-sources/security_user.md
- docs/resources/security_user.md
- nexus/data_source_security_user.go
- nexus/data_source_security_user_test.go
- nexus/data_source_user.go
- nexus/provider.go
- nexus/resource_security_user.go
- nexus/resource_security_user_test.go
- nexus/resource_user.go
> Proposal: Rename data_source_user{_test}.go -> data_source_security_user{_test}.go

- .github/workflows/feature-branches-pro.yaml
- .github/workflows/feature-branches.yaml
- docs/index.md
- go.mod
- go.sum
- nexus/data_source_security_saml_test.go
- nexus/resource_security_saml_test.go
> Fix update of resource nexus_security_ldap

- .github/workflows/feature-branches.yaml
- .github/workflows/release.yml
- go.mod
- go.sum
- chore(testing): Added minikube detection, updated .env to be sourced
- chore(golang): updated golang to 1.17
> go version 1.17

- nexus/resource_repository.go
Support bearerToken authentication in http clien configuration for npm repositories
> feat(repositories): Support bearerToken authentication

- docs/resources/repository.md
- go.mod
- go.sum
- nexus/resource_repository.go
- nexus/resource_repository_apt_proxy_test.go
> feat(repositories): Add conection options to repository manifest

- .github/workflows/codeql-analysis.yml
So that we get an insight of what we should / must improve!
> chore(codeql): enabled codeql-analysis workflow

- examples/resources/nexus_blobstore_file/resource.tf
- internal/services/deprecated/resource_repository.go
- internal/tools/main.go
> Fix pointer handling in resource nexus_repository

- docs/data-sources/repository_yum_hosted.md
- docs/resources/blobstore_file.md
- docs/resources/repository_yum_hosted.md
- internal/schema/repository/schema_cleanup.go
- internal/schema/repository/schema_component.go
- internal/schema/repository/schema_group.go
- internal/schema/repository/schema_http_client.go
- internal/schema/repository/schema_name.go
- internal/schema/repository/schema_negative_cache.go
- internal/schema/repository/schema_online.go
- internal/schema/repository/schema_proxy.go
- internal/schema/repository/schema_storage.go
- internal/services/repository/data_source_repository_yum_hosted.go
- internal/services/repository/flatten.go
- internal/services/repository/resource_repository_yum_hosted.go
- internal/services/repository/resource_repository_yum_hosted_test.go
Move common repsoitory schemas into own package
> feat(repository): Add component block to nexus_repository_yum_hosted

- internal/services/repository/resource_repository_docker_group_test.go
Attribute group.writable Member is a PRO feature
> fix(tests): Add SKIP_PRO_TEST to resource docker group test

- docs/resources/security_realms.md
- examples/resources/nexus_security_realms/import.sh
> fix(docs): Fix documentaton for import command of resource nexus_security_realms

- docs/resources/repository.md
- internal/services/deprecated/resource_repository.go
> docs(repository): Set deprecation Warning for old resource nexus_repository

- internal/schema/repository/schema_maven.go
- internal/services/repository/resource_repository_yum_hosted.go
- templates/data-sources.md.tmpl
- templates/resources.md.tmpl
docs: Improve doc generation templates
> feat(repository): Add validation function for maven and yum repo resources

- CODE_OF_CONDUCT.md
- README.md
Implements v2.1 of contributor-covenant.org code_of_conduct
https://www.contributor-covenant.org/version/2/1/code_of_conduct.html as
> chore: Add code of conduct

- .github/workflows/feature-branches.yaml
- GNUmakefile
- scripts/docker-compose.yml
- scripts/script.source
closes https://github.com/datadrivers/terraform-provider-nexus/issues/357
> chore: allow local development for m1

- .github/workflows/feature-branches.yaml
> ci: Enable pro tests in feature branch pipeline after getting new licence key

- docs/resources/repository_apt_proxy.md
- docs/resources/repository_bower_proxy.md
- docs/resources/repository_cocoapods_proxy.md
- docs/resources/repository_conan_proxy.md
- docs/resources/repository_conda_proxy.md
- docs/resources/repository_docker_proxy.md
- docs/resources/repository_go_proxy.md
- docs/resources/repository_helm_proxy.md
- docs/resources/repository_maven_proxy.md
- docs/resources/repository_npm_proxy.md
- docs/resources/repository_nuget_proxy.md
- docs/resources/repository_p2_proxy.md
- docs/resources/repository_pypi_proxy.md
- docs/resources/repository_r_proxy.md
- docs/resources/repository_raw_proxy.md
- docs/resources/repository_rubygems_proxy.md
- docs/resources/repository_yum_proxy.md
- internal/schema/repository/schema_negative_cache.go
> fix: Set negative_cache block to required

- docs/data-sources/repository_docker_hosted.md
- docs/resources/repository_docker_hosted.md
- go.mod
- go.sum
- internal/acceptance/template-strings-repository-docker.go
- internal/schema/repository/schema_docker.go
- internal/services/repository/data_source_repository_docker_hosted.go
- internal/services/repository/data_source_repository_docker_hosted_test.go
- internal/services/repository/flatten.go
- internal/services/repository/resource_repository_docker_hosted.go
- internal/services/repository/resource_repository_docker_hosted_test.go
> feat: Add latest_policy to storage block of docker hosted repository

- README.md
- scripts/.env
- scripts/docker-compose.yml
> feat: Update test nexus version to 3.80.0
